modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/North-West-Wind/forge-autofish/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/forge-autofish/master/update.json"
displayURL="https://github.com/North-West-Wind/forge-autofish/"
logoFile="forgeautofish.png"
credits="Thank you for using this mod"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"